services:
  - type: web
    name: krishiv
    env: python
    plan: standard # or free, depending on your choice
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: "3.10"  # Specify supported Python version
    envVariables:
      - key: DATABASE_URL
        fromDatabase: your-database-connection-string
      # Add other env vars like SECRET_KEY here
